version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # test to come, just want to see a successful deploy first...
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist